#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8007

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml       # mapper映射文件
  type-aliases-package: com.baihe.server.entity

spring:
  profiles: dev
  application:
    name: baihe-server-surveymanager #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/surveymanager?serverTimezone=GMT%2B8
    username: root
    password: 12345
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

---
server:
  port: 8007

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml       # mapper映射文件
  type-aliases-package: com.baihe.server.entity

spring:
  profiles: test
  application:
    name: baihe-server-surveymanager #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://172.17.0.2:3306/surveymanager?serverTimezone=GMT%2B8  # 数据库名称,db为jdk容器访问mysql容器指定的别名
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

---
server:
  port: 8007

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml       # mapper映射文件
  type-aliases-package: com.baihe.server.entity

spring:
  profiles: prod
  application:
    name: baihe-server-surveymanager #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.0.122:3306/surveymanager?serverTimezone=GMT%2B8  # 数据库名称,db为jdk容器访问mysql容器指定的别名
    username: root
    password: BandHagen88!@
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
