#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: prod # 激活开发环境配置
---
server:
  port: 80

spring:
  profiles: dev
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  #redis:
    #database: 0
    #host: localhost
    #port: 6379
    #password:

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    baiheintelligent:
      path: /baiheintelligent/**
      serviceId: baihe-server-baiheintelligent
    wechat:
      path: /wechat/**
      serviceId: baihe-server-wechat
    ai:
      path: /nlp/**
      serviceId: baihe-server-ai
    surveymanager:
      path: /surveymanager/**
      serviceId: baihe-server-surveymanager
    fastdfs:
      path: /fastdfs/**
      serviceId: baihe-server-fastdfs
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
logging:
  level:
    root: info
---
server:
  port: 80

spring:
  profiles: test
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  #redis:
    #database: 0
    #host: 172.17.0.7
    #port: 6379
    #password:

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      defaultZone: http://172.17.0.5:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    baiheintelligent:
      path: /baiheintelligent/**
      serviceId: baihe-server-baiheintelligent
    wechat:
      path: /wechat/**
      serviceId: baihe-server-wechat
    ai:
      path: /nlp/**
      serviceId: baihe-server-ai
    surveymanager:
      path: /surveymanager/**
      serviceId: baihe-server-surveymanager
    fastdfs:
      path: /fastdfs/**
      serviceId: baihe-server-fastdfs
      
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
---
server:
  port: 80

spring:
  profiles: prod
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  #redis:
    #database: 0
    #host: 172.17.0.9
    #port: 6379
    #password:

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      defaultZone: http://172.17.0.3:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 100000
  routes:
    baiheintelligent:
      path: /baiheintelligent/**
      serviceId: baihe-server-baiheintelligent
    wechat:
      path: /wechat/**
      serviceId: baihe-server-wechat
    ai:
      path: /nlp/**
      serviceId: baihe-server-ai
    surveymanager:
      path: /surveymanager/**
      serviceId: baihe-server-surveymanager
    fastdfs:
      path: /fastdfs/**
      serviceId: baihe-server-fastdfs
      
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000