#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 80

spring:
  profiles: dev
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  routes:
    provider-product:
      path: /quantification/**
      serviceId: baihe-server-baiheintelligent
      stripPrefix: false
      #如果多个服务需要经过路由，则同provider-product方式继续添加
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      defaultZone: http://172.17.0.2:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  routes:
    provider-quantification:
      path: /quantification/**
      serviceId: baihe-server-baiheintelligent
      stripPrefix: false
      #如果多个服务需要经过路由，则同provider-product方式继续添加
---
server:
  port: 7001

spring:
  profiles: prod
  application:
    name: baihe-server-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka,linux上配置ip域名映射
      #defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于baihe-server:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  routes:
    provider-quantification:
      path: /quantification/**
      serviceId: baihe-server-baiheintelligent
      stripPrefix: false
      #如果多个服务需要经过路由，则同provider-product方式继续添加